"""instrumentos ficha y filtros

Revision ID: 34da4d0b8f22
Revises: 7a8b9c1d2e3f
Create Date: 2026-09-28 11:48:59.092438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34da4d0b8f22'
down_revision: Union[str, Sequence[str], None] = '7a8b9c1d2e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento_recomendaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('recomendacion_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=180), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'recomendacion_id', name='uq_seguimiento_org_rec')
    )
    op.create_table('evaluacion_instrumentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluacion_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['cuestionario_versiones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'version_id', name='uq_eval_version_instrumento')
    )
    op.create_table('participante_instrumentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('instrumento_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrumento_id'], ['evaluacion_instrumentos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['evaluacion_participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id', 'instrumento_id', name='uq_participante_instrumento')
    )
    op.add_column('dimensiones', sa.Column('tipo', sa.String(length=20), nullable=False, server_default='DIMENSION'))

    op.add_column('dimensiones', sa.Column('factor_transformacion', sa.Float(), nullable=True))
    op.alter_column('evaluaciones', 'version_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('preguntas', sa.Column('tipo_respuesta', sa.String(length=20), nullable=False, server_default='LIKERT'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preguntas', 'tipo_respuesta')
    op.alter_column('evaluaciones', 'version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('dimensiones', 'factor_transformacion')
    op.drop_column('dimensiones', 'tipo')
    op.drop_table('participante_instrumentos')
    op.drop_table('evaluacion_instrumentos')
    op.drop_table('seguimiento_recomendaciones')
    # ### end Alembic commands ###
