"""filtro en preguntas

Revision ID: 5cd71dd1f202
Revises: 34da4d0b8f22
Create Date: 2026-09-28 14:38:59.688652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd71dd1f202'
down_revision: Union[str, Sequence[str], None] = '34da4d0b8f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preguntas', sa.Column('filtro', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preguntas', 'filtro')
    # ### end Alembic commands ###
