"""migracion_inicial

Revision ID: 60de8afddc4a
Revises: 
Create Date: 2026-09-15 09:13:18.734112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60de8afddc4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuestionario_versiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'numero_version', name='uq_cuestionario_version')
    )
    op.create_table('organizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('permisos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modulo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'nombre', name='uq_area_org_nombre')
    )
    op.create_table('dimensiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('dominio', sa.String(length=180), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['cuestionario_versiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permisos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    op.create_table('baremos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.Column('minimo', sa.Float(), nullable=False),
    sa.Column('maximo', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('inversa', sa.Boolean(), nullable=False),
    sa.Column('valor_minimo', sa.Integer(), nullable=False),
    sa.Column('valor_maximo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('numero_identificacion', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('organizacion_id', 'numero_identificacion', name='uq_trabajador_identificacion_org')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('entidad', sa.String(length=80), nullable=True),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('ip_origen', sa.String(length=64), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigos_verificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('evaluador_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('justificacion_cierre', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['cuestionario_versiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion_participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluacion_id', sa.UUID(), nullable=False),
    sa.Column('trabajador_id', sa.UUID(), nullable=False),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.Column('fecha_notificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'trabajador_id', name='uq_eval_trabajador')
    )
    op.create_table('informes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('trabajador_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('generado_por', sa.UUID(), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anonimizado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['generado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('evaluacion_id', sa.UUID(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consentimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('trabajador_id', sa.UUID(), nullable=False),
    sa.Column('aceptado', sa.Boolean(), nullable=False),
    sa.Column('texto_version', sa.String(length=40), nullable=False),
    sa.Column('ip_origen', sa.String(length=64), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['evaluacion_participantes.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id')
    )
    op.create_table('respuestas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('pregunta_id', sa.UUID(), nullable=False),
    sa.Column('valor_cifrado', sa.Text(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['evaluacion_participantes.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id', 'pregunta_id', name='uq_respuesta_pregunta')
    )
    op.create_table('resultados_dimension',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('puntaje_bruto', sa.Float(), nullable=False),
    sa.Column('puntaje_transformado', sa.Float(), nullable=False),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.Column('calculado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensiones.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['evaluacion_participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id', 'dimension_id', name='uq_resultado_dimension')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_dimension')
    op.drop_table('respuestas')
    op.drop_table('consentimientos')
    op.drop_table('notificaciones')
    op.drop_table('informes')
    op.drop_table('evaluacion_participantes')
    op.drop_table('evaluaciones')
    op.drop_table('codigos_verificacion')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('preguntas')
    op.drop_table('baremos')
    op.drop_table('roles_permisos')
    op.drop_table('dimensiones')
    op.drop_table('areas')
    op.drop_table('roles')
    op.drop_table('permisos')
    op.drop_table('organizaciones')
    op.drop_table('cuestionario_versiones')
    # ### end Alembic commands ###
