"""recrear_tabla_seguimiento

Revision ID: c9adf52ace26
Revises: 4b08bbb3221a
Create Date: 2026-09-30 17:18:14.123998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9adf52ace26'
down_revision: Union[str, Sequence[str], None] = '4b08bbb3221a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento_recomendaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('recomendacion_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=180), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'recomendacion_id', name='uq_seguimiento_org_rec')
    )
    op.add_column('organizaciones', sa.Column('creada_por_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_organizaciones_creada_por', 'organizaciones', 'usuarios', ['creada_por_id'], ['id'], use_alter=True)
    op.add_column('preguntas', sa.Column('filtro', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('foto_url', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('perfil_actualizado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'perfil_actualizado_en')
    op.drop_column('usuarios', 'foto_url')
    op.drop_column('preguntas', 'filtro')
    op.drop_constraint('fk_organizaciones_creada_por', 'organizaciones', type_='foreignkey')
    op.drop_column('organizaciones', 'creada_por_id')
    op.drop_table('seguimiento_recomendaciones')
    # ### end Alembic commands ###
